apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: flagger
  namespace: istio-system
spec:
  releaseName: flagger
  interval: 5m
    chart:
      spec:
        chart: flagger
        version: "1.7.0"
        sourceRef:
          kind: HelmRepository
          name: flagger
          namespace: flux-system
        interval: 1m
  values:
    meshProvider: istio
    metricsServer: http://prometheus.istio-system:9090
