apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: flagger-grafana
  namespace: istio-system
spec:
  releaseName: flagger-grafana
  interval: 5m
  chart:
    spec:
      chart: grafana
      version: "1.5.0"
      sourceRef:
        kind: HelmRepository
        name: flagger
        namespace: flux-system
      interval: 1m
  values:
    url: http://prometheus.istio-system:9090
